[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialMobilityAnalyzers = "050a7be8-18f9-52d6-bdba-0a194485d082"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
NumericIO = "6c575b1c-77cb-5640-a5dc-a54116c90507"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegularizationTools = "29dad682-9a27-4bc3-9c72-016788665182"
Underscores = "d9a01c3f-67ce-4d8c-9b55-35f6e4050bb1"
